### PR TITLE
v0.18 Release candidate

### PR DESCRIPTION
**Pull request by stevieb9**
Hey Sawyer,

I'm done with all of my changes.

Results for this PR:

Build results: https://travis-ci.org/stevieb9/test-ping/builds/113013936
Test coverage: https://coveralls.io/builds/5265963

Let me know if there's anything you don't like, and I'll update.

Cheers,

Steve

### CODE REVIEW

**Comment by xsawyerx** [comment]
Thank you for this PR!

I'd prefer to have it separate into the code changes and the distribution release changes, but I'd take it any way I can get it. :)

I still want to review further the `OBJPATH` solution before I merge it in. I hope to do it this weekend.

Thanks again!!

**Comment by stevieb9** [comment]
The $OBJPATH var was a bit confusing to me, so I'll do the same. I don't
really like how I worked around that area, so if you get some time to
consider it, I'd like if you kept me informed.

If I come up with anything better (after doing a far more detailed analysis
of the entire code), I'll let you know too.

Regards,

Steve

**Comment by xsawyerx** [comment]
Hi @stevieb9,

I've exhaustively reviewed this PR and merged almost all of it. I sifted through the commits and merged parts from each commit in layers and layers. First only the simple test changes, then the simple code changes, then reviewed the more complicated ones, then the distribution and release related.

I consider this merged and resolved.

However, the tests and code that required environment variables were left out. I do not want to have the module check for additional environment variables to change its behavior during a test. When that happens, it means the code is not decoupled enough.

If the attempt is to reach 100% coverage, we should try it again in some other way. We're now at 96.6%, which is still better.

Please go through the **master** branch, as it is merged in there and verify that the changes correspond to what you did. I kept your ID as the author for the changes, and I only introduced several smaller fixes, most of which in your commit already.

Once you've verified the changes, please close this PR as "resolved".

**Comment by stevieb9** [comment]
All looks good after I merged in your changes into my fork.

**Comment by xsawyerx** [comment]
Excellent. Cutting a release for this today.

We could work on the test coverage in another release. Might as well get this out meanwhile.

@stevieb9++

**Pull request closed without merging**
